### ISSUE TITLE
Provide a way to mannaully invoke instance view generation

### ISSUE THREAD

**Issue by daviszerro** [catbaron0/efb-mp-instanceview-middleware#3]
Currently, middleware works like a charm for its existing feature.

But sometimes the Wechat articles from where people send me in a chat, or articles I share to myself(文件传输助手), will not genrete instance view now. I think it will be perfect if this middleware adding feature to enable this.

Maybe a config file option, or a `/extra` command provide to Telegram master?

**Comment by catbaron0** [comment]
It should work now.
If you share an article to a chat, it should be processed by this middleware.
Not every article could be processed properly to enable the instant view feature, caused by the diversity of templates used by the Wechat Official Accounts. But usually the telegraph page is available anyway.
