### ISSUE TITLE
Bug for a specific article

### ISSUE THREAD

**Issue by realdeveloperongithub** [catbaron0/efb-mp-instanceview-middleware#4]
I tested several links and the middleware worked fine. But while testing this link: https://mp.weixin.qq.com/s/8zmYv704mUzkklr2HYZ2hA , an error was raised pointing to:

> "mp_to_telegraph.py", line 59, in publish
> return response['result']['url']
> KeyError: 'result'

Any idea how it is triggered?
Thanks

**Comment by catbaron0** [comment]
Thanks for reporting!

It seems to be caused by `<iframe>` to QQ videos.
A very long node is generated, and I got a ACCESS_TOKEN_INVALID error when publish the telegraph page.
Tried to fix this bug by convert `<iframe>` tag to `<a>` tag.
It should work, but I still can't watch the video directly ...
